# Change prefix to Ctrl-Space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Quality of life settings
set -g mouse on                          # Enable mouse for scrolling/resizing
set -g default-terminal "screen-256color" # Better colors
set -s escape-time 0                     # No delay for escape key (Vim friendly)
set -g history-limit 10000               # More scrollback history
set -g base-index 1                      # Start windows at 1
setw -g pane-base-index 1                # Start panes at 1
set -g renumber-windows on               # Close gaps in window numbering
set -g focus-events on
# set -g default-command "${SHELL}"        #Comment out in mac or non nixos
set -g allow-passthrough 
set -s set-clipboard on

# KEY BINDINGS
bind r source-file ~/.tmux.conf \; display "Config Reloaded!"

#Copy text when highlighting
setw -g mode-keys vi
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

# Split panes using | and - (and stay in current directory)
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
bind-key x kill-pane
unbind '"'
unbind %

# Move between panes with Prefix + h/j/k/l
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize panes with Prefix + H/J/K/L (Shifted)
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# VISUAL / STATUS BAR
set -g status-style bg=black,fg=white
set -g status-left-length 30
set -g status-left '#[fg=green](#S) '
set -g status-right ""
set -g pane-active-border-style "bg=default fg=blue"
# Highlight active window
set-window-option -g window-status-current-style bg=blue,fg=white
